services:
  redis:
    image: redis:7.4
    restart: always

  db:
    image: mariadb:11.5
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - 'db-data:/var/lib/mysql:Z'
      - './db-entrypoint.sql:/docker-entrypoint-initdb.d/db-entrypoint.sql'
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
    
  celery:
    build: ./site
    stdin_open: true
    env_file:
      - .env
    command: celery -A dmoj_celery worker
    depends_on:
      - redis

  site:
    build: ./site
    restart: always
    stdin_open: true
    env_file:
      - .env
    command: /startup.sh
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "localhost:8000"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 20
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      celery:
        condition: service_started

  bridged:
    build: ./site
    restart: always
    stdin_open: true
    env_file:
      - .env
    command: python3 manage.py runbridged
    depends_on:
      site:
        condition: service_healthy

  judge:
    build: ./judge
    restart: always
    volumes:
      - ./problems:/problems
    cap_add:
      - SYS_PTRACE
    command: run -c /problems/judge.yml bridged ${JUDGE_NAME} ${JUDGE_KEY}
    depends_on:
      - bridged

volumes:
  db-data: